#!/usr/bin/env bash

set -e

create(){
	touch "$1":"$(date +%d-%m-%Y)".md 
}

if [ -z "$1" ]; then
	echo "Please enter your topic name: "
	read -r topic
else
	topic="$1"
fi	

file_exists=false

for file in *"$topic".md; do
	if [ -f "$file" ]; then
		file_exists=true
		break;	
	fi
done

if [ "$file_exists" == true ]; then
	echo "Topic file already exists"
	exit 1
else
	create "$topic"
	exit 0
fi

